# Generated by Django 5.2.3 on 2025-06-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('foto', models.ImageField(upload_to='post/')),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
